"""
Setup script for Level 06: Creates S3 bucket, IAM role, and custom Code Interpreter
so that charts generated by Brew can be uploaded to S3 and shared via presigned URLs.

Run once: python3.11 setup_charts.py
"""

import boto3
import json
import time
import os

REGION = boto3.session.Session().region_name or os.getenv("AWS_DEFAULT_REGION", "us-west-2")
ACCOUNT_ID = boto3.client("sts", region_name=REGION).get_caller_identity()["Account"]

BUCKET_NAME = f"agentcore-cafe-charts-{ACCOUNT_ID}"
ROLE_NAME = "AmazonBedrockAgentCoreCafeCharts"
CI_NAME = "agentcore_cafe_charts"

s3 = boto3.client("s3", region_name=REGION)
iam = boto3.client("iam", region_name=REGION)
ssm = boto3.client("ssm", region_name=REGION)

print(f"☕ Setting up chart storage for account {ACCOUNT_ID} in {REGION}...")

# Step 1: Create S3 bucket
print(f"\n📦 Creating S3 bucket: {BUCKET_NAME}")
try:
    if REGION == "us-east-1":
        s3.create_bucket(Bucket=BUCKET_NAME)
    else:
        s3.create_bucket(Bucket=BUCKET_NAME, CreateBucketConfiguration={"LocationConstraint": REGION})
    print(f"   ✅ Bucket created")
except s3.exceptions.BucketAlreadyOwnedByYou:
    print(f"   ✅ Bucket already exists")
except Exception as e:
    if "BucketAlreadyExists" in str(e):
        print(f"   ✅ Bucket already exists")
    else:
        print(f"   ❌ Failed: {e}"); exit(1)

# Step 2: Create IAM role for Code Interpreter
print(f"\n🔐 Creating IAM role: {ROLE_NAME}")
trust_policy = {"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Principal": {"Service": "bedrock-agentcore.amazonaws.com"}, "Action": "sts:AssumeRole", "Condition": {"StringEquals": {"aws:SourceAccount": ACCOUNT_ID}}}]}
s3_policy = {"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Action": ["s3:PutObject", "s3:GetObject"], "Resource": f"arn:aws:s3:::{BUCKET_NAME}/*"}]}

try:
    iam.create_role(RoleName=ROLE_NAME, AssumeRolePolicyDocument=json.dumps(trust_policy), Description="Allows AgentCore Code Interpreter to upload charts to S3")
    print(f"   ✅ Role created")
except iam.exceptions.EntityAlreadyExistsException:
    print(f"   ✅ Role already exists")
iam.put_role_policy(RoleName=ROLE_NAME, PolicyName="S3ChartAccess", PolicyDocument=json.dumps(s3_policy))
ROLE_ARN = iam.get_role(RoleName=ROLE_NAME)["Role"]["Arn"]
print(f"   ⏳ Waiting 10s for IAM propagation...")
time.sleep(10)

# Step 3: Create custom Code Interpreter (PUBLIC mode for S3 access)
print(f"\n🖥️  Creating custom Code Interpreter: {CI_NAME}")
agentcore_control = boto3.client("bedrock-agentcore-control", region_name=REGION)
try:
    ci_response = agentcore_control.create_code_interpreter(name=CI_NAME, description="AgentCore Café chart generator with S3 access", executionRoleArn=ROLE_ARN, networkConfiguration={"networkMode": "PUBLIC"})
    ci_id = ci_response["codeInterpreterId"]
    print(f"   ✅ Created: {ci_id}")
except Exception as e:
    if "already exists" in str(e).lower() or "Conflict" in str(e):
        existing = agentcore_control.list_code_interpreters().get("codeInterpreterSummaries", [])
        ci_id = next(ci["codeInterpreterId"] for ci in existing if ci.get("name") == CI_NAME)
        print(f"   ✅ Already exists: {ci_id}")
    else:
        print(f"   ❌ Failed: {e}"); exit(1)

# Step 4: Add permissions to Runtime role
print(f"\n🔑 Adding permissions to Runtime role...")
runtime_role_name = None
# First: get role from actual agent runtime
try:
    ac = boto3.client("bedrock-agentcore-control", region_name=REGION)
    for a in ac.list_agent_runtimes().get("agentRuntimes", []):
        if "agentcore_cafe" in a.get("agentRuntimeName", ""):
            detail = ac.get_agent_runtime(agentRuntimeId=a["agentRuntimeId"])
            role_arn = detail.get("roleArn", detail.get("executionRoleArn", ""))
            if role_arn:
                runtime_role_name = role_arn.split("/")[-1]
                break
except Exception:
    pass
# Fallback: search IAM roles
if not runtime_role_name:
    for page in iam.get_paginator("list_roles").paginate():
        for role in page["Roles"]:
            if role["RoleName"].startswith("AmazonBedrockAgentCoreSDKRuntime"):
                runtime_role_name = role["RoleName"]
                break
        if runtime_role_name: break

if runtime_role_name:
    ci_arn = f"arn:aws:bedrock-agentcore:{REGION}:{ACCOUNT_ID}:code-interpreter-custom/{ci_id}"
    iam.put_role_policy(RoleName=runtime_role_name, PolicyName="CodeInterpreterCustomAndS3",
        PolicyDocument=json.dumps({"Version": "2012-10-17", "Statement": [
            {"Sid": "CustomCI", "Effect": "Allow", "Action": ["bedrock-agentcore:StartCodeInterpreterSession", "bedrock-agentcore:InvokeCodeInterpreter", "bedrock-agentcore:StopCodeInterpreterSession", "bedrock-agentcore:GetCodeInterpreter", "bedrock-agentcore:GetCodeInterpreterSession", "bedrock-agentcore:ListCodeInterpreterSessions"], "Resource": [ci_arn]},
            {"Sid": "S3Charts", "Effect": "Allow", "Action": ["s3:PutObject", "s3:GetObject", "s3:ListBucket"], "Resource": [f"arn:aws:s3:::{BUCKET_NAME}", f"arn:aws:s3:::{BUCKET_NAME}/*"]}
        ]}))
    print(f"   ✅ Added permissions to {runtime_role_name}")

# Step 5: Save to SSM
print(f"\n💾 Saving config to SSM...")
for key, val in [("charts_bucket", BUCKET_NAME), ("charts_ci_id", ci_id)]:
    ssm.put_parameter(Name=f"/agentcore-cafe/{key}", Value=val, Type="String", Overwrite=True)
    print(f"   ✅ /agentcore-cafe/{key} = {val}")

print(f"\n✅ Chart storage ready! Bucket: {BUCKET_NAME}, CI: {ci_id}")
print("   Now: agentcore deploy")
