name: GitHub Repo Stats                                                                                               
                                                                                                                      
on:                                                                                                                   
  schedule:                                                                                                           
    - cron: "30 11 * * *"                                                                                             
  workflow_dispatch:                                                                                                  
                                                                                                                      
jobs:                                                                                                                 
  stats:                                                                                                              
    runs-on: ubuntu-latest                                                                                            
    steps:                                                                                                            
      - uses: jgehrcke/github-repo-stats@v1.4.2                                                                       
        with:                                                                                                         
          ghtoken: ${{ secrets.GHRS_GITHUB_API_TOKEN }}
